In [1]:
import numpy as np

In [2]:
a = np.array([1,2,4,5])

In [3]:
print(a[0])

1


In [4]:
zero = np.zeros(2)

In [5]:
zero

array([0., 0.])

note that the type of the element of arrays is float

In [6]:
zeroint = np.zeros(2,dtype = np.int64)
zeroint

array([0, 0], dtype=int64)

ones is like zeros

now we go to arranging

In [7]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [8]:
np.linspace(2,11,num = 12)

array([ 2.        ,  2.81818182,  3.63636364,  4.45454545,  5.27272727,
        6.09090909,  6.90909091,  7.72727273,  8.54545455,  9.36363636,
       10.18181818, 11.        ])

#How do you know the shape and size of an array?

In [9]:
arr = np.array([[1,2,3,45,4],[6,2,6,1,8]])

In [10]:
arr.ndim

2

In [11]:
arr.size

10

In [12]:
arr.shape

(2, 5)