In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50])

In [3]:
b = np.arange(5)

In [4]:
a - b

array([10, 19, 28, 37, 46])

In [5]:
b**2

array([ 0,  1,  4,  9, 16])

In [6]:
10 * np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [7]:
a < 30

array([ True,  True, False, False, False])

In [8]:
A = np.array([[2,1],[4,9]])
B = np.array([[0,3],[2,0]])

In [10]:
A * B # element wise product

array([[0, 3],
       [8, 0]])

In [11]:
A @ B # matrix product

array([[ 2,  6],
       [18, 12]])

In [12]:
A.dot(B) # another matrix product

array([[ 2,  6],
       [18, 12]])

In [13]:
rg = np.random.default_rng(1)
a = np.ones((2,3),dtype = int)
b = rg.random((2, 3))


In [14]:
b += a

In [15]:
b

array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

In [16]:
a+=b
a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [17]:
a = rg.random((2,3))

In [18]:
a.sum()

3.1057109529998157

In [19]:
b = np.arange(12).reshape(3,4)

In [20]:
b.sum(axis=0)

array([12, 15, 18, 21])

axis = 0 is column and axis = 1 is row

In [21]:
a.sum(axis=1)

array([1.78649542, 1.31921554])

In [22]:
b.sum(axis=1)

array([ 6, 22, 38])

In [23]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [24]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])