In [1]:
import numpy as np

In [2]:
a = np.floor(10 * np.random.random((3,4)))
a

array([[3., 3., 9., 4.],
       [6., 4., 0., 7.],
       [4., 6., 6., 6.]])

In [3]:
a.shape

(3, 4)

In [4]:
a.ravel()

array([3., 3., 9., 4., 6., 4., 0., 7., 4., 6., 6., 6.])

In [5]:
a.T

array([[3., 6., 4.],
       [3., 4., 6.],
       [9., 0., 6.],
       [4., 7., 6.]])

In [6]:
a.T.shape

(4, 3)

In [7]:
a = a.reshape(4,3)
a

array([[3., 3., 9.],
       [4., 6., 4.],
       [0., 7., 4.],
       [6., 6., 6.]])

In [8]:
a.resize(3,4)

In [9]:
a

array([[3., 3., 9., 4.],
       [6., 4., 0., 7.],
       [4., 6., 6., 6.]])