In [1]:
import numpy as np

#axis0 = vertical = row
#axis1 = horizontal = column


In [2]:
a = np.floor(10*np.random.random((2,12)))
a

array([[8., 1., 3., 2., 2., 2., 9., 2., 7., 8., 5., 8.],
       [3., 7., 5., 8., 6., 1., 2., 2., 1., 9., 0., 7.]])

In [3]:
np.hsplit(a,3)

[array([[8., 1., 3., 2.],
        [3., 7., 5., 8.]]),
 array([[2., 2., 9., 2.],
        [6., 1., 2., 2.]]),
 array([[7., 8., 5., 8.],
        [1., 9., 0., 7.]])]

In [4]:
np.hsplit(a,(3,4))

[array([[8., 1., 3.],
        [3., 7., 5.]]),
 array([[2.],
        [8.]]),
 array([[2., 2., 9., 2., 7., 8., 5., 8.],
        [6., 1., 2., 2., 1., 9., 0., 7.]])]