In [1]:
import numpy as np

In [2]:
a = np.floor(10 * np.random.random((2, 2)))
a

array([[6., 1.],
       [7., 7.]])

In [3]:
b = np.floor(10 * np.random.random((2, 2)))

In [4]:
np.vstack((a,b))

array([[6., 1.],
       [7., 7.],
       [3., 1.],
       [0., 0.]])

In [5]:
np.hstack((a,b))

array([[6., 1., 3., 1.],
       [7., 7., 0., 0.]])

In [6]:
from numpy import newaxis

In [7]:
np.column_stack((a,b))

array([[6., 1., 3., 1.],
       [7., 7., 0., 0.]])

In [8]:
a = np.array([4., 2.])
b = np.array([5., 7.])

In [9]:
np.column_stack((a,b))

array([[4., 5.],
       [2., 7.]])

In [10]:
np.vstack((a,b))

array([[4., 2.],
       [5., 7.]])

In [11]:
np.hstack((a,b))

array([4., 2., 5., 7.])

#hstack does not suppose the 1d that is vector incontrast of column_stack

In [12]:
a[:, newaxis] # view `a` as a 2D column vector

array([[4.],
       [2.]])

In [13]:
np.column_stack((a[:,newaxis], b[:,newaxis]))

array([[4., 5.],
       [2., 7.]])

In [14]:
np.hstack((a[:, newaxis], b[:, newaxis]))  # the result is the same

array([[4., 5.],
       [2., 7.]])

In [15]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])