In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
np.argsort(a)

array([0, 1, 2, 3], dtype=int64)

In [4]:
b = np.array([3,2,9,1])

In [5]:
np.argsort(b)

array([3, 1, 0, 2], dtype=int64)

In [6]:
np.nonzero(b)

(array([0, 1, 2, 3], dtype=int64),)

In [7]:
np.where(a<2,a,a**2)

array([0, 1, 4, 9])