In [1]:
import numpy as np

In [2]:
a = np.arange(10)**3

In [3]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [4]:
for i in a:
    print(i**(1 / 3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [5]:
def f(x,y,z):
  return 10 * x + y + z

In [6]:
c = np.fromfunction(f,(2,3,2),dtype = int)
c

array([[[ 0,  1],
        [ 1,  2],
        [ 2,  3]],

       [[10, 11],
        [11, 12],
        [12, 13]]])

In [7]:
def f2(x,y):
  return 10 * x + y

In [8]:
b = np.fromfunction(f2,(6,5),dtype=int)
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [9]:
c[1,...]

array([[10, 11],
       [11, 12],
       [12, 13]])

In [10]:
c[...,1]

array([[ 1,  2,  3],
       [11, 12, 13]])

In [11]:
for row in b:
    print(row)

[0 1 2 3 4]
[10 11 12 13 14]
[20 21 22 23 24]
[30 31 32 33 34]
[40 41 42 43 44]
[50 51 52 53 54]


In [12]:
for element in b.flat:
  print(element)

0
1
2
3
4
10
11
12
13
14
20
21
22
23
24
30
31
32
33
34
40
41
42
43
44
50
51
52
53
54
